---
- include: ../../../tasks/erl_app.yml
  vars:
      name: soap_srv
      version: "{{soap_version}}"
      has_config: true
      data_dir: "{{base_data_dir}}/soap_srv/{{data_dir_suffix}}"
      log_dir: "{{base_log_dir}}/soap_srv/"
      user: "{{run_user}}"
