---
- name: Install Nginx
  yum: name=nginx-{{nginx_version}}
       state=present

- name: Enable Nginx service
  service: name=nginx
           enabled=true
           state=started

- name: Determine fastcgi IP address
  set_fact: poweralleyui_fastcgi_ip={{hostvars[inventory_hostname][poweralleyui_nic]['ipv4']['address']}}

- name: Provision config (1/3)
  copy: src={{item}} dest=/etc/nginx/{{item}}
  with_items:
  - nginx.conf
  - fastcgi_params
  notify: Restart Nginx

- name: Provision config (2/3)
  file: path=/etc/nginx/conf.d/{{item}} state=absent
  with_items:
  - default.conf
  - server.conf
  - ssl.conf
  - virtual.conf
  notify: Restart Nginx

- name: Provision config (3/3)
  template: src={{item}}.j2 dest=/etc/nginx/conf.d/{{item}}
  with_items:
  - poweralleyui.conf
  notify: Restart Nginx
