---
- name: Install Nginx
  yum: name=nginx-{{nginx_version}}
       state=present

- name: Enable Nginx service
  service: name=nginx
           enabled=true
           state=started

- name: Copy Nginx configuration
  copy: src={{item.src}} dest={{item.dest}}
  with_items:
  - {src: nginx.conf,
     dest: /etc/nginx/nginx.conf}
  - {src: server.conf,
     dest: /etc/nginx/conf.d/server.conf}
  - {src: fastcgi_params,
     dest: /etc/nginx/fastcgi_params}
  notify: Restart Nginx
