---
- name: Install HAProxy
  yum: name=haproxy-{{haproxy_version}}
       state=present

- name: Provision config
  template: src=haproxy.cfg.j2
            dest=/etc/haproxy/haproxy.cfg
  notify: Restart HAProxy

- name: Disable and don't start HAProxy service
  service: name=haproxy
           enabled=false
           state=stopped
