---
- name: Install HAProxy
  yum: name=haproxy-{{haproxy_version}}
       state=present

- name: Disable service
  service: name=haproxy
           enabled=false

- name: Provision config
  template: src=haproxy.cfg.j2
            dest=/etc/haproxy/haproxy.cfg
            backup=true
  notify: Reload HAProxy
