---
- name: Provision Cluster
  hosts: all
  sudo: true
  roles:
  - {role: drbd,    tags: ["drbd"],    when: "{{'drbd' in group_names}}"}
  - {role: cluster, tags: ["cluster"], when: "{{'cluster' in group_names}}"}
