---
- name: Provision PowerAlley test env
  hosts: all
  sudo: true
  tasks:
  - name: Copy start dev env script
    copy: src=files/start-dev-env
          dest=/opt/bin/
          mode=755

  - name: Setup autostart
    lineinfile: dest=/etc/rc.local
                line="su {{run_user}} -l -c 'bash -c \"/opt/bin/start-dev-env &>> /home/{{run_user}}/start-dev-env.log\"'"
    tags: ["autostart"]

- {include: provision-common-env.yml}
- {include: provision-backend-env.yml}
- {include: provision-frontend-env.yml}
- {include: deploy.yml, tags: ['funnel','soap','mm','email','oneapi','kelly','just','ui']}

- name: Post-install steps
  hosts: all
  sudo: true
  tasks:
  - name: Correct RabbitMQ rights
    file: path={{item}}
          owner={{run_user}}
          group={{run_user}}
          recurse=true
    with_items:
    - /opt/rabbitmq_server-{{rabbitmq_version}}
    - /var/lib/rabbitmq
    - /var/log/rabbitmq
    tags: ['post']

  - name: Install test deps
    yum: name={{item}}
         state=present
    with_items:
    - ansible
    - git
    tags: ['post']

  - name: Pull alley-ansible repo
    git: repo=https://github.com/ten0s/alley-ansible
         dest=/opt/ansible
    tags: ['post']

  - debug: msg='reboot'
  - debug: msg='copy and run http_conf.sh'
