---

#- hosts: staging
#  sudo: true
#  vars_files:
#  - vars/secrets.yml
#  roles:
#  - {role: mysql_remove, tags: ["mysql_remove"]}

- hosts: staging
  sudo: true
  vars_files:
  - vars/secrets.yml
  roles:
  - {role: mysql, tags: ["mysql"]}
 
