---
- name: Rename PowerAlley tables to lower case
  hosts: all
  sudo: true
  pre_tasks:
  - name: Stop PowerAlleyUI monitor
    supervisorctl: name=poweralleyui_monitor
                   state=stopped

  - name: Stop PowerAlleyUI
    supervisorctl: name=poweralleyui
                   state=stopped

  - name: Copy SQL script
    copy: src=rename_poweralley_tables.sql
          dest=/root/rename_poweralley_tables.sql

  - name: Run migration
    shell: mysql poweralley < /root/rename_poweralley_tables.sql
    register: rename_result
    failed_when: rename_result.rc != 0 and
                 ("already exists" not in rename_result.stderr)

  roles:
  - {role: "mysql"}

  post_tasks:
  - name: Start PowerAlleyUI
    supervisorctl: name=poweralleyui
                   state=started

  - name: Start PowerAlleyUI monitor
    supervisorctl: name=poweralleyui_monitor
                   state=started

  - name: Remove SQL script
    file: path=/root/rename_poweralley_tables.sql
          state=absent
