#!/bin/bash

ansible all -i inventories/artem -m ping && ansible-playbook deploy.yml -i inventories/artem --tags kelly && ansible all -i inventories/artem -s -U bms -m shell -a '/opt/kelly/bin/kelly stop; /opt/kelly/bin/kelly start'
