---
dependencies:
- {role: erl_app, name: mm_srv,
                  version: "{{mm_version}}",
                  data_dir: "{{base_data_dir}}/mm_srv/{{data_dir_suffix}}",
                  log_dir: "{{base_log_dir}}/mm_srv/",
                  user: "{{run_user}}"}
