---
- include: ../../../tasks/erl_app.yml
  vars:
      name: kelly
      version: "{{kelly_version}}"
      has_config: true
      data_dir: "{{base_data_dir}}/kelly/{{data_dir_suffix}}"
      log_dir: "{{base_log_dir}}/kelly/"
      user: "{{run_user}}"
