---
- include: ../../../tasks/erl_app.yml
  vars:
      name: mm_srv
      version: "{{mm_version}}"
      has_config: true
      data_dir: "{{base_data_dir}}/mm_srv/{{data_dir_suffix}}"
      log_dir: "{{base_log_dir}}/mm_srv/"
      user: "{{run_user}}"
