---
- include: ../../../tasks/erl_app.yml
  vars:
      name: just
      name_suffix: _mini
      version: "{{just_version}}"
      has_config: true
      data_dir: "{{base_data_dir}}/just/{{data_dir_suffix}}"
      log_dir: "{{base_log_dir}}/just/"
      user: "{{run_user}}"
