---
- include: ../../erlapp.yml
  vars:
      name: just
      name_suffix: _mini
      version: "{{just_version}}"

- name: "Provision config"
  template: src=sys.config.j2
            dest=/opt/just_mini-{{just_version}}/releases/1/sys.config
