---
- include: ../../../tasks/erl_app.yml
  vars:
      name: funnel
      name_suffix: _mini
      version: "{{funnel_version}}"
      has_config: true
      data_dir: "{{base_data_dir}}/funnel/{{data_dir_suffix}}"
      log_dir: "{{base_log_dir}}/funnel/"
      user: "{{run_user}}"
