# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.define "node1" do |node1|
    node1.vm.box = "ten0s/centos6.5_x86_64"
    node1.vm.network "private_network", ip: "192.168.100.201"
    node1.vm.network "forwarded_port", guest: 22, host: 2303
    node1.vm.provider "virtualbox" do |vb|
      vb.customize ["modifyvm", :id, "--memory", "1024"]
    end
  end

  config.vm.define "node2" do |node2|
    node2.vm.box = "ten0s/centos6.5_x86_64"
    node2.vm.network "private_network", ip: "192.168.100.202"
    node2.vm.network "forwarded_port", guest: 22, host: 2304
    node2.vm.provider "virtualbox" do |vb|
      vb.customize ["modifyvm", :id, "--memory", "1024"]
    end
  end

  config.vm.define "arbiter" do |arbiter|
    arbiter.vm.box = "ten0s/centos6.5_x86_64"
    arbiter.vm.network "private_network", ip: "192.168.100.203"
    arbiter.vm.network "forwarded_port", guest: 22, host: 2305
    arbiter.vm.provider "virtualbox" do |vb|
      vb.customize ["modifyvm", :id, "--memory", "512"]
    end
  end

  config.vm.define "arbiter2" do |arbiter2|
    arbiter2.vm.box = "ten0s/centos6.5_x86_64"
    arbiter2.vm.network "private_network", ip: "192.168.100.204"
    arbiter2.vm.network "forwarded_port", guest: 22, host: 2306
    arbiter2.vm.provider "virtualbox" do |vb|
      vb.customize ["modifyvm", :id, "--memory", "512"]
    end
  end

  config.vbguest.auto_update = false
end
