---
- name: Install deps
  yum: name={{item}} state=present
  with_items:
  - python-setuptools

- name: Install Supervisor & Plugin
  easy_install: name={{item}}
  with_items:
  - "supervisor=={{supervisor_version}}"
  - "superlance=={{superlance_version}}"

- name: Create Supervisor's config dir
  file: path={{item.path}} state=directory
        owner={{item.owner}} group={{item.group}}
  with_items:
  - {path: /etc/supervisor.d,
     owner: root,
     group: root}
  - {path: /opt/bin,
     owner: root,
     group: root}
  - {path: /var/log/pmm,
     owner: bms,
     group: bms}
  notify: Restart Supervisor

- name: Determine PowerAlleyUI fastcgi IP address
  set_fact: poweralleyui_fastcgi_ip={{hostvars[inventory_hostname][poweralleyui_nic]['ipv4']['address']}}
  when: poweralleyui_version is defined

- name: Determine WebMM fastcgi IP address
  set_fact: webmm_fastcgi_ip={{hostvars[inventory_hostname][webmm_nic]['ipv4']['address']}}
  when: webmm_version is defined

- name: Determine PowerAlleyUI http IP address (stg)
  set_fact: poweralleyui_http_ip={{poweralleyui_fastcgi_ip}}
  when: inventory_hostname != "node2" and poweralleyui_version is defined

- name: Determine PowerAlleyUI http IP address (prod)
  set_fact: poweralleyui_http_ip={{hostvars["arbiter"][poweralleyui_nic]['ipv4']['address']}}
  when: inventory_hostname == "node2" and poweralleyui_version is defined

- name: Determine WebMM http IP address (stg)
  set_fact: webmm_http_ip={{webmm_fastcgi_ip}}
  when: inventory_hostname != "node2" and webmm_version is defined

- name: Determine WebMM http IP address (prod)
  set_fact: webmm_http_ip={{hostvars["arbiter"][webmm_nic]['ipv4']['address']}}
  when: inventory_hostname == "node2" and webmm_version is defined

- name: Provision config (1/3)
  copy: src={{item.src}}
        dest={{item.dest}}
        mode={{item.mode}}
  with_items:
  - {src: etc/supervisord.conf, dest: /etc/supervisord.conf, mode: 644}
  - {src: etc/init.d/supervisord, dest: /etc/init.d/supervisord, mode: 755}
  notify: Restart Supervisor

- name: Provision config (2/3)
  template: src={{item.src}}
            dest={{item.dest}}
            mode={{item.mode}}
  with_items:
  - {src: poweralleyui.conf.j2, dest: /etc/supervisor.d/poweralleyui.conf, mode: 644}
  - {src: poweralleyui.sh.j2, dest: /opt/bin/poweralleyui.sh, mode: 755}
  notify: Restart Supervisor
  when: poweralleyui_version is defined

- name: Provision config (3/3)
  template: src={{item.src}}
            dest={{item.dest}}
            mode={{item.mode}}
  with_items:
  - {src: webmm.conf.j2, dest: /etc/supervisor.d/webmm.conf, mode: 644}
  - {src: webmm.sh.j2, dest: /opt/bin/webmm.sh, mode: 755}
  notify: Restart Supervisor
  when: webmm_version is defined

- name: Enable Supervisor service
  service: name=supervisord
           enabled=true
           state=started
  notify: Restart Supervisor
