---
- name: Install MySQL playbook's deps
  yum: name={{item}} state=latest
  with_items:
  - MySQL-python

- name: Install MySQL
  yum: name=mysql-server-{{mysql_version}}
       state=present

- name: Provision config
  copy: src=my.cnf
        dest=/etc/my.cnf
  notify: Restart MySQL

- name: Enable MySQL service
  service: name=mysqld
           enabled=true
           state=started

- name: Create DB (1/2)
  mysql_db: name=poweralley
            state=present
  notify: Restart MySQL
  when: poweralleyui_version is defined

- name: Create DB (2/2)
  mysql_db: name={{item}}
            state=present
  notify: Restart MySQL
  with_items:
  - webmm
  - phonebook
  - localization
  when: webmm_version is defined

- name: Setup DB priviledges
  mysql_user: name={{mysql_username}}
              host={{item}}
              password={{mysql_password}}
              priv=*.*:ALL,GRANT
              state=present
  mysql_user: name={{mysql_username}}
              host={{item}}
              password={{mysql_password}}
              priv=*.*:ALL,GRANT
              state=present
  with_items:
  - localhost
  - '%'
  notify: Restart MySQL
