---
- name: Install SMPPSim
  yum: name=pmm-smppsim-{{smppsim_version}}
       state=present

- name: Provision config
  copy: src={{item}}
        dest=/opt/smppsim-{{smppsim_version}}/conf/
  with_items:
  - smppsim.props
  - logging.properties

- name: Create link
  file: src=/opt/smppsim-{{smppsim_version}}
        dest=/opt/smppsim
        state=link
