---
- name: Create DB
  mysql_db: name=poweralley
            state=present

- name: Install app repo
  template: src={{item}}.j2
        dest=/etc/yum.repos.d/{{item}}
        mode=644
  with_items:
  - pmm-poweralleyui-dev.list
  - pmm-poweralleyui-rc.list
  - pmm-poweralleyui.repo

- name: Install app
  yum: name=pmm-bms-poweralleyui-pmm-{{poweralleyui_version}}
       state=present
       update_cache=true
       disablerepo="*"
       enablerepo="pmm-poweralleyui-dev,pmm-poweralleyui-rc"
  notify: Restart PowerAlleyUI

- name: Provision config (1/2)
  template: src=ConnectionStrings.config.j2
            dest=/opt/poweralleyui/Configs/ConnectionStrings.config
  notify: Restart PowerAlleyUI
  
- name: Provision config (2/2)
  template: src=AppSettings.config.j2
            dest=/opt/poweralleyui/Configs/AppSettings.config
  notify: Restart PowerAlleyUI

- name: Correct rights
  file: path=/opt/poweralleyui
        owner={{run_user}}
        group={{run_user}}
        recurse=true
        follow=true
  notify: Restart PowerAlleyUI
