---
- name: Install PMM-BankAudi repo
  copy: src=pmm-bankaudi.repo
        dest=/etc/yum.repos.d/pmm-bankaudi.repo
        mode=644

- name: Add PMM-BankAudi Rel repo list
  copy: src=pmm-bankaudi-rel.list
        dest=/etc/yum.repos.d/pmm-bankaudi-rel.list
        mode=644

- name: Add PMM-BankAudi Dev repo list
  copy: src=pmm-bankaudi-dev.list
        dest=/etc/yum.repos.d/pmm-bankaudi-dev.list
        mode=644

- name: Install PowerAlleyUI
  yum: name=pmm-bms-poweralleyui-bankaudi-{{poweralleyui_version}}
       state=present
       update_cache=true
  notify: Restart Supervisor

- name: Provision config
  template: src=Web.config.j2
            dest=/opt/poweralleyui-{{poweralleyui_version}}/Web.config
  notify: Restart Supervisor

- name: Correct rights
  file: path=/opt/poweralleyui-{{poweralleyui_version}}
        owner={{run_user}}
        group={{run_user}}
        recurse=true
        follow=true
  notify: Restart Supervisor

- name: Create link
  file: src=/opt/poweralleyui-{{poweralleyui_version}}
        dest=/opt/poweralleyui
        state=link
  notify: Restart Supervisor
