---
- name: Install PMM-BankAudi repo
  copy: src=pmm-bankaudi.repo
        dest=/etc/yum.repos.d/pmm-bankaudi.repo
        mode=644

- name: Add PMM-BankAudi Rel repo list
  copy: src=pmm-bankaudi-rel.list
        dest=/etc/yum.repos.d/pmm-bankaudi-rel.list
        mode=644

- name: Add PMM-BankAudi Dev repo list
  copy: src=pmm-bankaudi-dev.list
        dest=/etc/yum.repos.d/pmm-bankaudi-dev.list
        mode=644

- name: Install PowerAlleyUI
  yum: name=pmm-bms-poweralleyui-bankaudi-{{poweralleyui_version}}
       state=present
       update_cache=true
       disablerepo="*"
       enablerepo="pmm-bankaudi-rel,pmm-bankaudi-dev"
  notify: Restart Supervisor

- name: Provision config
  template: src=ConnectionStrings.j2
            dest=/opt/poweralleyui/Configs/ConnectionStrings.config
  notify: Restart Supervisor

- name: Correct rights
  file: path=/opt/poweralleyui
        owner={{run_user}}
        group={{run_user}}
        recurse=true
        follow=true
  notify: Restart Supervisor
