---
- name: Install tests repo
  template: src={{item}}.j2
        dest=/etc/yum.repos.d/{{item}}
        mode=644
  with_items:
  - pmm-tests-dev.list
  - pmm-tests-rc.list
  - pmm-tests.repo

- name: Install tests
  yum: name=pmm-bms-poweralleyui-tests-{{poweralleyui_version}}
       state=present
       update_cache=true
       disablerepo="*"
       enablerepo="pmm-tests-dev"

- name: Create tests result dir
  file: path=/opt/poweralleyui-tests-results/{{poweralleyui_version}}
        state=directory
        owner={{run_user}}
        group={{run_user}}
        recurse=true

- name: Copy tests starter script
  copy: src=starter_poweralleyui_tests.sh
        dest=/opt/bin/starter_poweralleyui_tests.sh
        mode=755

- name: Provision tests configs (1/2)
  template: src={{item}}.appSettings.config.j2
            dest=/opt/poweralleyui-tests/PowerAlleyUI.{{item}}/appSettings.config
  with_items:
  - KellyApiTests
  - UITests

- name: Provision tests configs (2/2)
  template: src=ConnectionStrings.config.j2
            dest=/opt/poweralleyui-tests/PowerAlleyUI.UITests/ConnectionStrings.config
