---
- name: Rename PowerAlley tables to lower case
  hosts: all
  sudo: true
  tasks:
  - name: Copy SQL script
    copy: src=rename_poweralley_tables.sql
          dest=/root/rename_poweralley_tables.sql

  - name: Run migration
    shell: mysql poweralley < /root/rename_poweralley_tables.sql
    register: rename_result
    failed_when: rename_result.rc != 0 and
                 ("already exists" not in rename_result.stderr)

  - name: Remove SQL script
    file: path=/root/rename_poweralley_tables.sql
          state=absent
