---
- name: Install Mono
  yum: name={{item}} state=present
  with_items:
  - libgdiplus
  - libgdiplus-devel
  - pmm-mono-{{mono_version}}

- name: Add Mono env to /etc/profile
  lineinfile: dest=/etc/profile
              regexp='^source /opt/mono'
              backrefs=true
              line='source /opt/mono-{{mono_version}}/env.rc'
