#!/bin/bash

if [[ "$(id -un)" == "root" ]]; then
    echo "Must not be root"
    exit 1
fi

echo
date +'%F %T'
echo

echo -e "\nStarting RabbitMQ..."
rabbitmq-server -detached
sleep 30
rabbitmqctl status
if [ $? != 0 ]; then
    echo "FAILED"
else
    echo "SUCCESS"
fi

echo -e "\nStarting SMPPSim..."
$(cd /opt/smppsim; ./startsmppsim.sh) &
echo "SUCCESS"

echo -e "\nStarting SMPPSink..."
/opt/smppsink/bin/smppsink start
sleep 10
S=`/opt/smppsink/bin/smppsink ping`
if [[ $S != 'pong' ]]; then
    echo $S
    echo "FAILED"
else
    echo "SUCCESS"
fi

if [[ -x /opt/funnel/bin/funnel ]]; then
    echo -e "\nStarting Funnel..."
    /opt/funnel/bin/funnel start
    sleep 10
    F=`/opt/funnel/bin/funnel ping`
    if [[ $F != 'pong' ]]; then
        echo $F
        echo "FAILED"
    else
        echo "SUCCESS"
    fi
fi

if [[ -x /opt/soap_srv/bin/soap_srv ]]; then
    echo -e "\nStarting SOAP..."
    /opt/soap_srv/bin/soap_srv start
    sleep 10
    S=`/opt/soap_srv/bin/soap_srv ping`
    if [[ $S != 'pong' ]]; then
        echo $S
        echo "FAILED"
    else
        echo "SUCCESS"
    fi
fi

if [[ -x /opt/oneapi_srv/bin/oneapi_srv ]]; then
    echo -e "\nStarting OneAPI..."
    /opt/oneapi_srv/bin/oneapi_srv start
    sleep 10
    O=`/opt/oneapi_srv/bin/oneapi_srv ping`
    if [[ $O != 'pong' ]]; then
        echo $O
        echo "FAILED"
    else
        echo "SUCCESS"
    fi
fi

if [[ -x /opt/mm_srv/bin/mm_srv ]]; then
    echo -e "\nStarting MM..."
    /opt/mm_srv/bin/mm_srv start
    sleep 10
    M=`/opt/mm_srv/bin/mm_srv ping`
    if [[ $M != 'pong' ]]; then
        echo $M
        echo "FAILED"
    else
        echo "SUCCESS"
    fi
fi

if [[ -x /opt/email2sms/bin/email2sms ]]; then
    echo -e "\nStarting Email2SMS..."
    /opt/email2sms/bin/email2sms start
    sleep 10
    E=`/opt/email2sms/bin/email2sms ping`
    if [[ $E != 'pong' ]]; then
        echo $E
        echo "FAILED"
    else
        echo "SUCCESS"
    fi
fi

if [[ -x /opt/kelly/bin/kelly ]]; then
    echo -e "\nStarting Kelly..."
    /opt/kelly/bin/kelly start
    sleep 10
    K=`/opt/kelly/bin/kelly ping`
    if [[ $K != 'pong' ]]; then
        echo $K
        echo "FAILED"
    else
        echo "SUCCESS"
    fi
fi

if [[ -x /opt/just/bin/just ]]; then
    echo -e "\nStarting Just..."
    /opt/just/bin/just start
    sleep 20
    J=`/opt/just/bin/just ping`
    if [[ $J != 'pong' ]]; then
        echo $J
        echo "FAILED"
    else
        echo "SUCCESS"
    fi
fi
