#!/bin/bash

if [[ "$(id -un)" == "root" ]]; then
    echo "Must not be root"
    exit 1
fi

echo
date +'%F %T'
echo

echo -e "\nStarting RabbitMQ..."
rabbitmq-server -detached
sleep 30
rabbitmqctl status
if [ $? != 0 ]; then
    echo "FAILED"
else
    echo "SUCCESS"
fi

echo -e "\nStarting SMPPSim..."
$(cd /opt/smppsim; ./startsmppsim.sh) &
echo "SUCCESS"

echo -e "\nStarting SMPPSink..."
/opt/smppsink/bin/smppsink start
sleep 10
S=`/opt/smppsink/bin/smppsink ping`
if [[ $S != 'pong' ]]; then
    echo $S
    echo "FAILED"
else
    echo "SUCCESS"
fi
