---
- name: Install ha-clustering.repo
  copy: src=ha-clustering.repo
        dest=/etc/yum.repos.d/ha-clustering.repo
        mode=644

- name: Install packages (1/2)
  yum: name={{item}} state=present
  with_items:
  - ccs-0.16.2
  - cman-3.0.12.1
  - pcs-0.9.123

- name: Install packages (2/2)
  yum: name={{item}} state=present enablerepo=ha-clustering
  with_items:
  - crmsh-2.1
  - pacemaker-1.1.12 # pacemaker/corosync /1.1.12/1.4.7 # prod 1.1.10/1.4.5
  - pssh-2.3.1
  - resource-agents-3.9.6 # prod 3.9.5

- name: Copy configs (1/2)
  template: src=cluster.conf.j2
        dest=/etc/cluster/cluster.conf
        backup=true
  tags: ['configs']

- name: Copy configs (2/2)
  copy: src={{item.src}}
        dest={{item.dest}}
        backup=true
  with_items:
  - {src: "cman", dest: "/etc/sysconfig/cman"}
  - {src: "cluster_init_conf.cib", dest: "/etc/cluster/cluster_init_conf.cib"}
  tags: ['configs']

- name: Copy resource agents
  copy: src={{item.src}}
        dest={{item.dest}}
        backup=true
        mode=755
  with_items:
  - {src: "rebarred", dest: "/usr/lib/ocf/resource.d/pmm/"}
  - {src: "rabbitmq-server", dest: "/usr/lib/ocf/resource.d/rabbitmq/"}
  tags: ['agents']

#- name: Copy script
#  copy: src=corosync_failcount_clear
#        dest=/usr/local/sbin/corosync_failcount_clear
#        owner=root
#        group=root
#        mode=755

- name: Enable and start CMAN & Pacemaker services # OR use rc.local???
  service: name={{item}}
           enabled=true
           state=started
  with_items:
  - cman
  - pacemaker

# rc.local
# node1:sleep 5 &&  su root -l -c 'bash -c "/etc/init.d/cman start && /etc/init.d/pacemaker start"'
# node2:sleep 15 && su root -l -c 'bash -c "/etc/init.d/cman start && /etc/init.d/pacemaker start"'
# arbiter:          su root -l -c 'bash -c "/etc/init.d/cman start && /etc/init.d/pacemaker start"'
# arbiter2:         su root -l -c 'bash -c "/etc/init.d/cman start && /etc/init.d/pacemaker start"'

# ???
#template "/etc/corosync/cluster_init_config.cib"
