---
- name: Install ha-clustering.repo
  copy: src=ha-clustering.repo
        dest=/etc/yum.repos.d/ha-clustering.repo
        mode=644

- name: Install packages (1/2)
  yum: name={{item}} state=present
  with_items:
  - ccs-0.16.2
  - cman-3.0.12.1
  - pcs-0.9.123

- name: Install packages (2/2)
  #
  # ha-clustering is disabled by default because
  # it may (and usually will) conflict with base
  #
  yum: name={{item}} state=present enablerepo=ha-clustering
  with_items:
  - crmsh-2.1
  # i'm very sceptical about setup pacemaker from this repository
  - pacemaker-1.1.12 # pacemaker/corosync /1.1.12/1.4.7 # prod 1.1.10/1.4.5
  - resource-agents-3.9.6 # prod 3.9.5

- name: Disable CMAN & Pacemaker services
  service: name={{item}}
           enabled=false
           state=stopped
  with_items:
  - cman
  - pacemaker

- name: Copy configs
  copy: src={{item.src}}
        dest={{item.dest}}
        backup=true
  with_items:
  - {src: "cluster.conf", dest: "/etc/cluster/cluster.conf"}
  - {src: "cman", dest: "/etc/sysconfig/cman"}

- name: Ensure log dir exists
  file: path="/var/log/cluster"
        owner=root
        group=root
        mode=755
        state=directory

- name: Copy script
  copy: src=corosync_failcount_clear
        dest=/usr/local/sbin/corosync_failcount_clear
        owner=root
        group=root
        mode=755

# rc.local
# node1:sleep 5 &&  su root -l -c 'bash -c "/etc/init.d/cman start && /etc/init.d/pacemaker start"'
# node2:sleep 15 && su root -l -c 'bash -c "/etc/init.d/cman start && /etc/init.d/pacemaker start"'
# arbiter:          su root -l -c 'bash -c "/etc/init.d/cman start && /etc/init.d/pacemaker start"'
# arbiter2:         su root -l -c 'bash -c "/etc/init.d/cman start && /etc/init.d/pacemaker start"'

# ???
#template "/etc/corosync/cluster_init_config.cib"
