---
- name: Setup PowerAlley backend
  hosts: all
  sudo: true

  roles:
  - {role: common, tags: ["common"]}
  - {role: funnel, tags: ["funnel"]}
  - {role: soap_srv, tags: ["soap"]}
  - {role: mm_srv, tags: ["mm"]}
  - {role: oneapi_srv, tags: ["oneapi"]}
  - {role: kelly, tags: ["kelly"]}
  - {role: just, tags: ["just"]}
  - {role: smppsink, tags: ["smppsink"]}
