---
- name: Setup
  hosts: all
  sudo: true
  vars:
  ## ?!? to erl_app defaults
  - base_data_dir: /var/lib
  - base_log_dir: /var/log
  - download_dir: /tmp
  - has_config: false
  - http_proxy: ""
  - name_suffix: ""
  - user: bms # !! doesn't work :(
  tasks:
  - include: tasks/common.yml

  - include: tasks/erl_app.yml
    vars:
        name: funnel
        name_suffix: _mini
        version: "{{funnel_version}}"
        has_config: true
        data_dir: "{{base_data_dir}}/funnel/"
        log_dir: "{{base_log_dir}}/funnel/"


  - include: tasks/erl_app.yml
    vars:
        name: soap_srv
        version: "{{soap_version}}"
        has_config: true
        data_dir: "{{base_data_dir}}/soap_srv/"
        log_dir: "{{base_log_dir}}/soap_srv/"

  - include: tasks/erl_app.yml
    vars:
        name: mm_srv
        version: "{{mm_version}}"
        has_config: true
        data_dir: "{{base_data_dir}}/mm_srv/"
        log_dir: "{{base_log_dir}}/mm_srv/"

  - include: tasks/erl_app.yml
    vars:
        name: oneapi_srv
        version: "{{oneapi_version}}"
        has_config: true
        data_dir: "{{base_data_dir}}/oneapi_srv/"
        log_dir: "{{base_log_dir}}/oneapi_srv/"

  - include: tasks/erl_app.yml
    vars:
        name: kelly
        version: "{{kelly_version}}"
        has_config: true
        data_dir: "{{base_data_dir}}/kelly/"
        log_dir: "{{base_log_dir}}/kelly/"

  - include: tasks/erl_app.yml
    vars:
        name: just
        name_suffix: _mini
        version: "{{just_version}}"
        has_config: true
        data_dir: "{{base_data_dir}}/just/"
        log_dir: "{{base_log_dir}}/just/"

  - include: tasks/erl_app.yml
    vars:
        name: smppsink
        version: "{{smppsink_version}}"
        has_config: true
