---
- name: Setup
  hosts: all
  sudo: true
  vars:
  - run_user: bms
  # erl_app defaults
  - base_data_dir: /var/lib
  - data_dir_suffix: ""
  - base_log_dir: /var/log
  - download_dir: /tmp
  - has_config: false
  - http_proxy: ""
  - name_suffix: ""

  roles:
  - base
  - funnel
  - soap_srv
  - mm_srv
  - oneapi_srv
  - kelly
  - just
  - smppsink
