---
- name: Setup
  hosts: all
  sudo: true
  vars:
  - run_user: bms

  roles:
  - {role: common, user: "{{run_user}}"}
  - funnel
  - soap_srv
  - mm_srv
  - oneapi_srv
  - kelly
  - just
  - smppsink
