---
- name: Install deps
  yum: name={{item}} state=present
  with_items:
  - tokyocabinet

- include: ../../erlapp.yml
  vars:
      name: funnel
      name_suffix: _mini
      version: "{{funnel_version}}"

- name: Provision config
  template: src=sys.config.j2
            dest=/opt/funnel_mini-{{funnel_version}}/releases/1/sys.config
