---
- include: ../../../tasks/erl_app.yml
  vars:
      name: oneapi_srv
      version: "{{oneapi_version}}"
      has_config: true
      data_dir: "{{base_data_dir}}/oneapi_srv/{{data_dir_suffix}}"
      log_dir: "{{base_log_dir}}/oneapi_srv/"
      user: "{{run_user}}"
