---
- name: Copy backup script
  copy: src=backup_dbs.sh dest=/root/backup_dbs.sh mode=0755

- name: Backup Databases
  shell: /root/backup_dbs.sh

- name: Stop MySQL
  service: name=mysqld state=stopped

- name: Remove MySQL
  yum: name={{ item }} state=absent
  with_items:
  - mysql-server
  - mysql
  - mysql-libs

- name: Backup MySQL dir
  shell: rsync -aH /var/lib/mysql /var/lib/mysql-$(date +%T).sql

- name: Remove MySQL dir
  shell: rm -rf /var/lib/mysql
